### ISSUE TITLE
RectangleIntersect on an XYZM coordinate sequence fails - Invalid ordinate index: 3

### ISSUE THREAD

**Issue by ianturton** [locationtech/jts#793] opened 2021-11-01 11:22 UTC
This is the root cause of https://osgeo-org.atlassian.net/browse/GEOS-10290 when GeoServer/GeoTools tries to access a XYZM shapefile we get the following exception thrown. This is because a `PackedCoordinateSequence` will happily handle the M and Z elements but when `RectangleIntersects` line 327 calls `getCoordinate` on the sequence it passes in a `Coordinate` as the destination and that always throws an exception when `setM()` is called (as is the case if the sequence has an M value!).  

```
Caused by: java.lang.IllegalArgumentException: Invalid ordinate index: 3
	at org.locationtech.jts.geom.Coordinate.setM(Coordinate.java:218)
	at org.locationtech.jts.geom.impl.PackedCoordinateSequence.getCoordinate(PackedCoordinateSequence.java:116)
	at org.locationtech.jts.operation.predicate.RectangleIntersectsSegmentVisitor.checkIntersectionWithSegments(RectangleIntersects.java:327)
	at org.locationtech.jts.operation.predicate.RectangleIntersectsSegmentVisitor.checkIntersectionWithLineStrings(RectangleIntersects.java:317)
	at org.locationtech.jts.operation.predicate.RectangleIntersectsSegmentVisitor.visit(RectangleIntersects.java:310)
	at org.locationtech.jts.geom.util.ShortCircuitedGeometryVisitor.applyTo(ShortCircuitedGeometryVisitor.java:35)
	at org.locationtech.jts.operation.predicate.RectangleIntersects.intersects(RectangleIntersects.java:110)
	at org.locationtech.jts.operation.predicate.RectangleIntersects.intersects(RectangleIntersects.java:58)
	at org.locationtech.jts.geom.Geometry.intersects(Geometry.java:754)
```

**Comment by dr-jts** [comment] 2021-11-01 21:30
Ah yes, more whack-a-mole with the extended coordinate dimension model.

The fix is going to be to allocate coordinates of the proper dimension by calling `createCoordinate` on the coordinate sequence passed to `RectangleIntersectsSegmentVisitor.checkIntersectionWithSegments`.  Hope to get that rolled out soon.

**Comment by jnh5y** [comment] 2021-11-01 21:40
@dr-jts If we (I suppose I am volunteering Jody and me) wanted to check on things ahead of time, would reviewing all calls to `createCoordinate` help find this issues?

**Comment by dr-jts** [comment] 2021-11-01 22:04
@jnh5y In fact I have just done that, and it shows this problem is widespread.  The fix is probably straightforward in most or all cases - i.e. use `createCoordinate` as mentioned above.  

A bit shocking this hasn't shown up before.  You could certainly help fix this.  And of course would be good to add unit tests to ensure that it is fixed.

**Comment by jnh5y** [comment] 2021-11-01 22:19
Hmm... I'm only seeing the method called in these classes:
```
modules/core/src/main/java/org/locationtech/jts/geom/impl/CoordinateArraySequence.java
modules/core/src/main/java/org/locationtech/jts/operation/predicate/RectangleIntersects.java
modules/core/src/test/java/org/locationtech/jts/geom/impl/CoordinateSequenceTestBase.java
modules/io/common/src/main/java/org/locationtech/jts/io/geojson/GeoJsonReader.java
```

Admittedly, I'm looking quickly with `git grep`, so maybe I'm missing something else.

Any thoughts on the easiest way to identify and knock out the work?  Should we have a single PR for the fixes?  Or would it make sense to break it into fixes/issues/PRs per class?  (I'm wondering if it'd make it easy for me and Jody to volunteer fixes.)

**Comment by jnh5y** [comment] 2021-11-01 22:21
Oh wait... the issue is with `new Coordinate()`, right?  Nevermind...  yeah, this is gonna take some thought/coordination/work.

**Comment by dr-jts** [comment] 2021-11-01 22:24
Using Eclipse Show References:
![image](https://user-images.githubusercontent.com/3529053/139750023-6267a94b-8dfe-402c-b928-3746ee6c6efd.png)

**Comment by jnh5y** [comment] 2021-11-01 22:26
Oh, sorry to have reopened this issue.  I thought I had closed it with a comment.  My bad!  Closing it (again).

**Closed by jnh5y** 2021-11-01 22:26 UTC
Labels: type-bug, jts-core

**Comment by dr-jts** [comment] 2021-11-01 22:27
It should be a fairly mechanical change for most if not all of the occurrences.

At least a sprinkling of unit tests to cover this would be good.  I think an efficient way to do this is to make a `XYZMTest` class (probably in the `geom` package) with a `PackedCoordinateSequence` factory, and then call a bunch of ops which will hit the various places that will fail.

**Comment by jnh5y** [comment] 2021-11-01 22:29
That does sound like a sane approach.  I could take a crack at some time after this week.  I don't know where it fits in your list of things to worry about.  (Basically, don't let me hold this up if it is trivial.  Also, if it is a PITA, I'm happy to help at some point.)

**Comment by dr-jts** [comment] 2021-11-01 22:35
> That does sound like a sane approach. I could take a crack at some time after this week. 

That would be great, @jnh5y .
