### ISSUE TITLE
Java multipoint buffer memory overflow, what's a good way

### ISSUE THREAD

**Issue by liukuankuan** [locationtech/jts#913] opened 2022-10-11 12:31 UTC
After recognizing the map, our program generates multiple points, and then buffer the memory overflow. After I debug the single point buffer, it is OK, and after simplification, the memory overflow will occur again. If single point buffer and simplification are used, the final result seems to be wrong. What's a good method

The following is the detailed code：
        BufferOp bufOp = new BufferOp(geometry);
        bufOp.setEndCapStyle(BufferParameters.CAP_SQUARE);
        Geometry geometryBuffer = bufOp.getResultGeometry(bufferDistance);

       Geometry geometryBufferSimplify = VWSimplifier.simplify(geometryBuffer, 0.05);

The coordinateArray is more than 400000

![image](https://user-images.githubusercontent.com/30552390/195091982-12fcf80e-9c91-4e0e-a113-d1de4be6e3d0.png)

**Comment by mprins** [comment] 2022-10-11 14:24
the full stack trace would be helpful analysing your problem

**Comment by dr-jts** [comment] 2022-10-11 15:36
As would input data that reproduces the problem.  The description of the
problem isn't clear to me at all.

**Comment by mprins** [comment] 2022-10-12 11:21
Your report is still missing key information for debugging and/or analysis, but the essence is you need more memory for your program; this may help: https://www.baeldung.com/java-gc-overhead-limit-exceeded

**Comment by liukuankuan** [comment] 2022-10-13 06:52
Thank you for your answer. I adjusted the jvm memory size to 5G in the local idea Exe program observation, to bufOp The getResultGeometry (bufferDistance) line of code will be gc. It is reasonable to say that the size of the jvm is enough. Why is gc still needed?

**Comment by l2365775436** [comment] 2022-12-22 10:03
哥们，你的问题解决了吗？我现在也是程序报内存溢出

**Comment by dr-jts** [comment] 2024-12-19 19:32
Closing since no feedback given.

**Closed by dr-jts** 2024-12-19 19:32 UTC
Labels: type-question
