### ISSUE TITLE
Unexpected union of two MultiPolygons

### ISSUE THREAD

**Issue by grimsa** [locationtech/jts#825] opened 2022-01-04 21:04 UTC
This is likely also caused by high-precision numbers, similar to https://github.com/locationtech/jts/issues/784 and https://github.com/locationtech/jts/issues/820.

JTS version used: 1.18.2 with OverlayNG enabled.

Can be reproduced by copy-pasting WKT to JTS TestBuilder:
A:
`MULTIPOLYGON (((1.4020000000000001 0.6152725855529207, 2.017272585552921 0, 0 0, 0 2.0172725855529214, 0.6152725855529207 1.4020000000000001, 1.4020000000000001 1.4020000000000001, 1.4020000000000001 0.6152725855529207)), 
  ((3.9999999999999996 0, 2.0172725856347586 0, 3.0086362927764605 0.9913637072235397, 3.9999999999999996 0)), 
  ((0.9913637072235395 3.0086362927764605, 0 2.017272585634758, 0 3.9999999999999996, 0.9913637072235395 3.0086362927764605)))`

B: 
`MULTIPOLYGON (((1.4020000000000001 0.6152725856097978, 1.4020000000000001 1.4020000000000001, 0.6152725855778813 1.4020000000000001, -0.0000000000000002 2.017272585552921, 0.9913637072235395 3.0086362927764605, 3.0086362927764605 0.9913637072235397, 2.0172725856347586 0.0000000000000001, 1.4020000000000001 0.6152725856097978)))`

Result of A union B:
`
GEOMETRYCOLLECTION (POLYGON ((2.017272585552921 0, 0 0, 0 2.017272585552921, 0 2.0172725855529214, 0.0000000000000002 2.0172725855529214, 0.9913637072235395 3.0086362927764605, 3.0086362927764605 0.9913637072235397, 2.0172725856347586 0.0000000000000001, 1.4020000000000001 0.6152725856097978, 1.4020000000000001 0.6152725855529207, 2.017272585552921 0), 
  (0.6152725855529207 1.4020000000000001, 0.6152725855778813 1.4020000000000001, 0.0000161232623158 2.0172564622906055, 0.6152725855529207 1.4020000000000001)), 
  POLYGON ((2.0172725856347586 0, 3.0086362927764605 0.9913637072235397, 3.9999999999999996 0, 2.0172725856347586 0)), 
  POLYGON ((0 2.017272585634758, 0 3.9999999999999996, 0.9913637072235395 3.0086362927764605, 0 2.017272585634758)), 
  LINESTRING (0 2.017272585552921, -0.0000000000000002 2.017272585552921))
`

![image](https://user-images.githubusercontent.com/8446128/148123772-55c79dce-dcdd-497f-9731-49eb970ecd0f.png)

Expected result:
- Ideally, a single polygon
- Alternatively, a multipolygon (the 3 polygons without the almost 0-length linestring)

**Comment by dr-jts** [comment] 2022-01-04 21:12
Wow, that's a bad one.  Thanks for the report.

**Comment by dr-jts** [comment] 2022-01-04 21:30
This is actually working as designed.  

The input is not fully aligned - as can be seen using the TestBuilder in **Reveal Topology** mode: 
![image](https://user-images.githubusercontent.com/3529053/148125407-0c653c12-04f3-4767-9a69-2d9775051bdd.png)
The union result simply reflects this misalignment.
![image](https://user-images.githubusercontent.com/3529053/148126364-1effd891-6723-4ac6-bcc6-d439dd870eb6.png)

The reason the result is heterogeneous (i.e. including the additional LineString) is for legacy reasons, to match the semantics of the original overlay implementation.  OverlayNG does provide a [**strict mode**](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/operation/overlayng/OverlayNG.java#L401), which allows forcing results to be homogeneous.

**Comment by dr-jts** [comment] 2022-01-05 02:58
Also note that the `SnappingNoder` can be used  explicitly with OverlayNG (in code, and in the TestBuilder).  Using snapping can eliminate the input misalignment. 

![image](https://user-images.githubusercontent.com/3529053/148153762-30f58114-f73f-4d41-85e4-ebb88ab45bff.png)

With a suitable snapping distance (here 1E-7) the result is a single triangle polygon:
```
POLYGON ((0 0, 0 2.0172725855529214, 0 3.9999999999999996, 0.9913637072235395 3.0086362927764605, 3.0086362927764605 0.9913637072235397, 3.9999999999999996 0, 2.017272585552921 0, 0 0))
```
![image](https://user-images.githubusercontent.com/3529053/148153471-88ac5fe4-ee3d-4cd3-913e-ab0c15380e48.png)

**Comment by grimsa** [comment] 2022-01-05 17:11
Thank you for a quick investigation and a thorough explanation.

The Reveal Topology looks very useful, thank you. Took me a while to find it 😅
In case anyone stumbles upon this later, you can find it here:
![image](https://user-images.githubusercontent.com/8446128/148256047-59de52c9-958a-4bb4-8f35-cd7f24183f05.png)

It seems that ultimately we should use both `SnappingNoder` and the strict overlay mode in our application - that seems like a simpler solution than post-processing the result (what we currently do).

I looked into the code a bit, and did not find a way to configure this via system properties or `Geometry#*` operations (that we currently use).
In the other issue you mentioned [OverlayNGSnappingFunctions code](https://github.com/locationtech/jts/blob/master/modules/app/src/main/java/org/locationtech/jtstest/function/OverlayNGSnappingFunctions.java). It would seem that implementing some utility class/wrapper that provides a more convenient API on top of the `OverlayNG` operations is the intended approach when configuration knobs have to be tinkered with? I'll try that in near future.

Should I close the issue now that it's clear that it's not a bug?

**Comment by dr-jts** [comment] 2022-01-05 18:14
Yes, implementing a (set of) wrapper functions providing an API for the OverlayNG settings you want is a good approach. 

I'll close this now.

**Closed by dr-jts** 2022-01-05 18:14 UTC
Labels: type-question, jts-core-overlay, status-NO ACTION
